<a href="https://colab.research.google.com/github/DiegozRM/Clase_GIt/blob/master/PruebaExamen.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [176]:
import os
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import RandomOverSampler

In [177]:

os.chdir("/content/Datos")
datos = pd.read_csv('DatasetVirus.csv',delimiter=',',decimal=".")
print(datos.shape)
print(datos.head())
print(datos.info())

(108, 35)
     Nombre       Ala    B       Cys       Asp       Glu       Phe       Gly  \
0  AB014795  1.869159  0.0  1.869159  0.934579  7.476636  1.869159  6.542056   
1  AF062029  3.680982  0.0  3.680982  2.453988  5.521472  3.067485  7.975460   
2  AF062031  3.246753  0.0  3.896104  2.597403  5.194805  3.246753  7.142857   
3  AF062033  3.164557  0.0  3.797468  2.531646  3.797468  3.164557  8.860759   
4  AF107771  6.698565  0.0  1.435407  4.784689  9.090909  3.827751  7.655502   

        His        Ile  ...  Z  Num Amino Acidos  Peso Molecular  pI Teorico  \
0  1.869159  10.280374  ...  0               107        12204.05        9.86   
1  2.453988  11.042945  ...  0               163        17929.58        8.92   
2  2.597403  11.038961  ...  0               154        17112.73        9.05   
3  2.531646   9.493671  ...  0               158        17393.91        9.43   
4  5.263158   2.870813  ...  0               209        24021.07        5.99   

   Carbon  Hidrogeno  Nitrog

In [178]:
X = datos.iloc[0:,1:34]
print(X.head())

        Ala    B       Cys       Asp       Glu       Phe       Gly       His  \
0  1.869159  0.0  1.869159  0.934579  7.476636  1.869159  6.542056  1.869159   
1  3.680982  0.0  3.680982  2.453988  5.521472  3.067485  7.975460  2.453988   
2  3.246753  0.0  3.896104  2.597403  5.194805  3.246753  7.142857  2.597403   
3  3.164557  0.0  3.797468  2.531646  3.797468  3.164557  8.860759  2.531646   
4  6.698565  0.0  1.435407  4.784689  9.090909  3.827751  7.655502  5.263158   

         Ile       Lys  ...       Tyr  Z  Num Amino Acidos  Peso Molecular  \
0  10.280374  7.476636  ...  1.869159  0               107        12204.05   
1  11.042945  7.975460  ...  2.453988  0               163        17929.58   
2  11.038961  8.441558  ...  3.246753  0               154        17112.73   
3   9.493671  7.594937  ...  3.164557  0               158        17393.91   
4   2.870813  5.741627  ...  3.827751  0               209        24021.07   

   pI Teorico  Carbon  Hidrogeno  Nitrogeno  Oxige

In [179]:
y = datos.iloc[:,34:35]
print(y.head())

  Clasificacion
0          R5X4
1          R5X4
2          R5X4
3          R5X4
4          R5X4


In [180]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, random_state=0)

In [181]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

oversampler = RandomOverSampler()
X_resampled, y_resampled = oversampler.fit_resample(X_train_scaled, y_train.iloc[:, 0].values)

In [182]:
instancia_red = MLPClassifier(solver='lbfgs', random_state=0, max_iter=1000, hidden_layer_sizes=(500, 50), learning_rate_init=0.001)

print(instancia_red)

MLPClassifier(hidden_layer_sizes=(500, 50), max_iter=1000, random_state=0,
              solver='lbfgs')


In [183]:
instancia_red.fit(X_resampled, y_resampled)

# Realiza predicciones en el conjunto de prueba
predicciones = instancia_red.predict(X_test_scaled)

In [184]:
print("Las predicciones en Testing son: {}".format(predicciones))

Las predicciones en Testing son: ['R5' 'R5X4' 'R5' 'R5X4' 'R5' 'X4' 'X4' 'X4' 'X4' 'X4' 'R5' 'R5' 'R5' 'R5'
 'X4' 'R5' 'R5' 'X4' 'X4' 'R5' 'R5' 'R5']


In [185]:
def indices_general(MC, nombres=None):
    precision_global = np.sum(MC.diagonal()) / np.sum(MC)
    error_global = 1 - precision_global
    return {"Matriz de Confusión": MC, "Precisión Global": precision_global, "Error Global": error_global}


In [186]:
print("Dimensiones de y_test:", y_test.shape)
print("Dimensiones de predicciones:", predicciones.shape)


Dimensiones de y_test: (22, 1)
Dimensiones de predicciones: (22,)


In [187]:
MC = confusion_matrix(y_test, predicciones)
indices = indices_general(MC, list(np.unique(y_test)))

for k in indices:
    print("\n%s:\n%s" % (k, str(indices[k])))

#scores = cross_val_score(instancia_red, X_train_scaled, y_train.iloc[:, 0].values, cv=3)  # Reducir el número de divisiones
#print("Precisión media de la validación cruzada:", np.mean(scores))


Matriz de Confusión:
[[7 0 0]
 [2 2 2]
 [3 0 6]]

Precisión Global:
0.6818181818181818

Error Global:
0.31818181818181823


In [188]:
import os
import pandas as pd
import numpy  as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix
from pandas import DataFrame
from matplotlib import colors as mcolors
import os
import pandas as pd

os.chdir("/content/Datos")
datos = pd.read_csv('DatasetVirus.csv',delimiter=',',decimal=".")
print(datos.shape)
print(datos.head())
print(datos.info())

X = datos.iloc[0:,1:34]
print(X.head())
y = datos.iloc[:,34:35]
print(y.head())

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, random_state=0)

instancia_red = MLPClassifier(solver='lbfgs', random_state=0)
print(instancia_red)

instancia_red.fit(X_train,y_train.iloc[:,0].values)

print("Las predicciones en Testing son: {}".format(instancia_red.predict(X_test)))

def indices_general(MC, nombres = None):
    precision_global = np.sum(MC.diagonal()) / np.sum(MC)
    error_global = 1 - precision_global
   # precision_categoria  = pd.DataFrame(MC.diagonal()/np.sum(MC,axis = 1)).T
   # if nombres!=None:
      #  precision_categoria.columns = nombres
    return {"Matriz de Confusión":MC,
            "Precisión Global":precision_global,
            "Error Global":error_global}
        #    "Precisión por categoría":precision_categoria}

prediccion = instancia_red.predict(X_test)
MC = confusion_matrix(y_test, prediccion)
indices = indices_general(MC,list(np.unique(y)))
for k in indices:
    print("\n%s:\n%s"%(k,str(indices[k])))

(108, 35)
     Nombre       Ala    B       Cys       Asp       Glu       Phe       Gly  \
0  AB014795  1.869159  0.0  1.869159  0.934579  7.476636  1.869159  6.542056   
1  AF062029  3.680982  0.0  3.680982  2.453988  5.521472  3.067485  7.975460   
2  AF062031  3.246753  0.0  3.896104  2.597403  5.194805  3.246753  7.142857   
3  AF062033  3.164557  0.0  3.797468  2.531646  3.797468  3.164557  8.860759   
4  AF107771  6.698565  0.0  1.435407  4.784689  9.090909  3.827751  7.655502   

        His        Ile  ...  Z  Num Amino Acidos  Peso Molecular  pI Teorico  \
0  1.869159  10.280374  ...  0               107        12204.05        9.86   
1  2.453988  11.042945  ...  0               163        17929.58        8.92   
2  2.597403  11.038961  ...  0               154        17112.73        9.05   
3  2.531646   9.493671  ...  0               158        17393.91        9.43   
4  5.263158   2.870813  ...  0               209        24021.07        5.99   

   Carbon  Hidrogeno  Nitrog

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:541: ConvergenceWarning: lbfgs failed to converge (status=2):
ABNORMAL_TERMINATION_IN_LNSRCH.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
